# Generated by Django 6.0.5 on 2026-05-30 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('usd_fx_rate', models.FloatField(default=0)),
                ('eur_fx_rate', models.FloatField(default=0)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, default='', max_length=16)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DayNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('text', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DayPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
            options={
                'ordering': ['-date_from'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('render_type', models.CharField(choices=[('years', 'Years'), ('months', 'Months'), ('seasons', 'Seasons')], default='seasons', max_length=16)),
                ('events_feed_type', models.CharField(choices=[('feed', 'Feed'), ('historical', 'Historical')], default='historical', max_length=16)),
                ('year_from', models.IntegerField(blank=True, null=True)),
                ('year_to', models.IntegerField(blank=True, null=True)),
                ('search_string', models.CharField(blank=True, default='', max_length=255)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('type', models.IntegerField(choices=[(1, 'Single event'), (2, 'Recurring event'), (3, 'Period')], default=1)),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, default='')),
                ('color', models.CharField(blank=True, default='', max_length=16)),
                ('date', models.DateField(blank=True, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('date_type', models.IntegerField(blank=True, choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Yearly')], help_text='Recurrence cadence (recurring events only).', null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='events', to='calendar_app.category')),
            ],
            options={
                'ordering': ['date', 'date_from', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PatternAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('hours', models.PositiveIntegerField(default=0)),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(blank=True, default='', max_length=16)),
                ('exclude_weekend', models.BooleanField(default=False)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='calendar_app.daypattern')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
