# Generated by Django 6.0.5 on 2026-05-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patternaction',
            name='pattern',
        ),
        migrations.DeleteModel(
            name='DayPattern',
        ),
        migrations.DeleteModel(
            name='PatternAction',
        ),
    ]
