# Generated by Django 6.0.5 on 2026-05-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_remove_patternaction_pattern_delete_daypattern_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
