# Generated by Django 6.0.5 on 2026-05-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_delete_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='important',
            field=models.BooleanField(default=False, help_text='A major event / achievement, shown in the Years view.'),
        ),
    ]
