# Generated by Django 6.0.5 on 2026-05-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_event_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='exclude_weekends',
            field=models.BooleanField(default=False, help_text='Period events: skip Saturdays and Sundays (e.g. work).'),
        ),
    ]
