# Generated by Django 6.0.5 on 2026-05-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0005_event_exclude_weekends'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='background',
            field=models.BooleanField(default=False, help_text='Render as a subtle background status, not a prominent event (long-term periods).'),
        ),
    ]
