# Generated by Django 6.0.5 on 2026-05-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0007_event_created_at_event_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='excluded_categories',
            field=models.ManyToManyField(blank=True, help_text='Categories hidden in the Life-in-weeks view.', related_name='+', to='calendar_app.category'),
        ),
    ]
