# Generated by Django 6.0.5 on 2026-06-07 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0008_settings_excluded_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('active', 'Active'), ('achieved', 'Achieved'), ('dropped', 'Dropped')], default='idea', max_length=16)),
                ('color', models.CharField(blank=True, default='', max_length=16)),
                ('achieved_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='calendar_app.daynote')),
            ],
            options={
                'ordering': ['status', '-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='calendar_app.goal')),
            ],
            options={
                'ordering': ['year'],
                'unique_together': {('goal', 'year')},
            },
        ),
    ]
