# Generated by Django 6.0.5 on 2026-06-07 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0009_goal_goalyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('target_age', models.PositiveIntegerField(help_text='Age by which to reach this milestone.')),
                ('weekly_hours', models.FloatField(default=0, help_text='Free hours available per week.')),
                ('money_budget', models.FloatField(default=0, help_text='Total money available for the period.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['target_age'],
            },
        ),
        migrations.AddField(
            model_name='goal',
            name='done_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='goal',
            name='unit_cost',
            field=models.FloatField(default=0, help_text='Money per item.'),
        ),
        migrations.AddField(
            model_name='goal',
            name='unit_hours',
            field=models.FloatField(default=0, help_text='Hours per item.'),
        ),
        migrations.AddField(
            model_name='goal',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='calendar_app.milestone'),
        ),
    ]
