# Generated by Django 6.0.5 on 2026-06-07 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0010_milestone_goal_done_count_goal_target_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='done_count',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='target_count',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='unit_hours',
        ),
        migrations.CreateModel(
            name='MilestoneRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('hours', models.FloatField(default=0, help_text='Free-time hours this consumes.')),
                ('cost', models.FloatField(default=0, help_text='Cost in euro.')),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='calendar_app.milestone')),
            ],
            options={
                'ordering': ['date_from', 'title'],
            },
        ),
    ]
