# Generated by Django 6.0.5 on 2026-06-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0011_remove_goal_done_count_remove_goal_milestone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestonerecord',
            name='milestone',
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
        migrations.DeleteModel(
            name='MilestoneRecord',
        ),
    ]
