# Generated by Django 6.0.5 on 2026-06-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0012_remove_milestonerecord_milestone_delete_milestone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daynote',
            options={'ordering': ['-date', 'created_at']},
        ),
        migrations.AddField(
            model_name='daynote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='daynote',
            name='date',
            field=models.DateField(),
        ),
    ]
